version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8000"
    volumes:
      - ./backend:/src
      - ./backend/config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python3 manage.py makemigrations && python manage.py migrate && gunicorn ippo_tutor.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./backend:/src
    expose:
      - "8000"
