# Generated by Django 2.1 on 2018-09-01 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ippo_tutor.apps.tasks.models
import ippo_tutor.apps.works.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_auto_20180827_0716'),
        ('works', '0006_auto_20180901_2313'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=511)),
                ('zip_with_templates', models.FileField(null=True, storage=ippo_tutor.apps.works.models.OverwriteStorage(), upload_to=ippo_tutor.apps.tasks.models.upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('changed', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Subject')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.SubjectType')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutors.TutorProfile')),
            ],
        ),
    ]
