# Generated by Django 2.1.1 on 2018-09-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180827_0716'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Subject'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.SubjectType'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='changed',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'group', 'subject', 'subject_type')},
        ),
    ]
