# Generated by Django 2.1 on 2018-08-29 22:19

from django.db import migrations, models
import django.db.models.deletion
import ippo_tutor.apps.works.models
import ippo_tutor.apps.core.storage

class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20180828_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(null=True, upload_to=ippo_tutor.apps.core.storage.upload_work),
        ),
        migrations.AlterField(
            model_name='work',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='students.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='tutors.TutorProfile'),
        ),
    ]
