# Generated by Django 2.1 on 2018-08-31 17:03

from django.db import migrations, models
import ippo_tutor.apps.works.models
import ippo_tutor.apps.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20180830_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(null=True, storage=ippo_tutor.apps.core.storage.OverwriteStorage(), upload_to=ippo_tutor.apps.core.storage.upload_work),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('F', 'To fix'), ('N', 'Not done')], default='N', max_length=1),
        ),
    ]
