# Generated by Django 2.1 on 2018-09-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20180831_1703'),
        ('works', '0003_auto_20180829_2219'),
    ]

    operations = [
    ]
