# Generated by Django 2.1.1 on 2018-09-23 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ippo_tutor.apps.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180827_0716'),
        ('tasks', '0002_auto_20180923_2336'),
        ('works', '0006_auto_20180901_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='document',
            field=models.FileField(null=True, storage=ippo_tutor.apps.core.storage.OverwriteStorage(), upload_to=ippo_tutor.apps.core.storage.upload_work, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='work',
            name='source_code',
            field=models.FileField(null=True, storage=ippo_tutor.apps.core.storage.OverwriteStorage(), upload_to=ippo_tutor.apps.core.storage.upload_work, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AddField(
            model_name='work',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='work',
            name='file',
        ),
        migrations.RemoveField(
            model_name='work',
            name='loaded',
        ),
        migrations.RemoveField(
            model_name='work',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='work',
            name='subject_type',
        ),
        migrations.RemoveField(
            model_name='work',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('task', 'student')},
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectType',
        ),
    ]
